name: book_review_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  pedantic_mono: any
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
